---
title: "inferencia-wikimedia"
output: html_document
---

```{r setup}
library(tidyverse)
library(here)
library(lubridate)
library(boot)
library(broom)
theme_set(theme_bw())
```

```{r ETL}
buscas = read_csv(here::here("data/search_data.csv"))
names(buscas)[names(buscas) == "session_start_date"] <- "search_time"
```

### clickthrough rate com p-valor

```{r}

buscas.por.sessao <- buscas %>% group_by(session_id, group) %>% 
    summarise(session_length = first(session_length), 
              search_time = first(search_time), 
              sum_clicks = sum(num_clicks),
              sum_results = sum(results)) %>%
    ungroup()


theta_diff_rate = function(buscas, i){
    rates = buscas %>%
        slice(i) %>%
        group_by(group) %>% 
        summarise(rate = sum(sum_clicks > 0)/n()) 
    
    group.a = rates %>% filter(group == "a") %>% pull(rate)
    group.b = rates %>% filter(group == "b") %>% pull(rate)
    
    group.a - group.b
}

theta_embaralhado = function(buscas){
    rates = buscas %>% 
        mutate(grupo_embaralhado = sample(group, n())) %>% 
        group_by(grupo_embaralhado) %>% 
        summarise(rate = sum(sum_clicks > 0)/n()) 
    
    group.a = rates %>% filter(grupo_embaralhado == "a") %>% pull(rate)
    group.b = rates %>% filter(grupo_embaralhado == "b") %>% pull(rate)
    
    group.a - group.b
}



theta_embaralhado(buscas.por.sessao)
theta_c <- theta_diff_rate(buscas.por.sessao, 1:NROW(buscas.por.sessao))


diffs1 = replicate(2000, {theta_embaralhado(buscas.por.sessao)})
tibble(diferenca = diffs1) %>% 
  ggplot(aes(x = diferenca)) + 
  # geom_histogram(binwidth = .2, fill = "white", color = "darkgreen") + 
    geom_density(fill = "white", color = "darkgreen") + 
  geom_vline(xintercept = theta_diff_rate(buscas.por.sessao, 1:NROW(buscas.por.sessao)), 
             color = "orange") + 
    geom_vline(xintercept = - theta_diff_rate(buscas.por.sessao, 1:NROW(buscas.por.sessao)), 
             color = "orange") + 
    geom_rug()


p.value <- mean(abs(diffs1) >= abs(theta_diff_rate(buscas.por.sessao, 1:NROW(buscas.por.sessao))))
p.value
```


### clickthrough rate com IC

```{r}
bootstrap = function(df){
  boot <- sample_n(df,           
                   size = NROW(df),
                   replace = TRUE)
  
  rates = boot %>%
        group_by(group) %>% 
        summarise(rate = sum(sum_clicks > 0)/n()) 
    
    group.a = rates %>% filter(group == "a") %>% pull(rate)
    group.b = rates %>% filter(group == "b") %>% pull(rate)
    
    diff <- group.a - group.b 
  
  return(diff)
}

repeticoes <- 2000
reamostragens = tibble(i = 1:repeticoes) %>% 
  mutate(theta_c_s = map_dbl(i, ~ bootstrap(buscas.por.sessao)))

erro.amostral = reamostragens %>% 
  mutate(erro = theta_c_s - theta_c)

intervalo = erro.amostral %>% 
  summarise(erro_i = quantile(erro, .025), 
            erro_s = quantile(erro, .975))
intervalo

ci = intervalo %>% 
  mutate(valor_i = theta_c + erro_i, 
         valor_s = theta_c + erro_s)
ci$valor_i
ci$valor_s
```




### Proporção de buscas com zero resultados com p-valor

```{r}

theta_diff_zero_results_rate = function(buscas, i){
    zero_results_rates = buscas %>%
        slice(i) %>%
        group_by(group) %>% 
        summarise(zero_results_rate = sum(results == 0)/n()) 
    
    group.a = zero_results_rates %>% filter(group == "a") %>% pull(zero_results_rate)
    group.b = zero_results_rates %>% filter(group == "b") %>% pull(zero_results_rate)
    
    group.a - group.b
}

theta_embaralhado_zero_results = function(buscas){
    zero_results_rates = buscas %>% 
        mutate(grupo_embaralhado = sample(group, n())) %>% 
        group_by(grupo_embaralhado) %>% 
        summarise(zero_results_rate = sum(results == 0)/n()) 
    
    group.a = zero_results_rates %>% filter(grupo_embaralhado == "a") %>% pull(zero_results_rate)
    group.b = zero_results_rates %>% filter(grupo_embaralhado == "b") %>% pull(zero_results_rate)
    
    group.a - group.b
}

theta_embaralhado_zero_results(buscas)
theta_c_zero <- theta_diff_zero_results_rate(buscas, 1:NROW(buscas))

diffs_zero_results = replicate(2000, {theta_embaralhado_zero_results(buscas)})
p.value <- mean(abs(diffs_zero_results) >= abs(theta_diff_zero_results_rate(buscas, 1:NROW(buscas))))
p.value

```

### Zero results rate com IC
```{r}

bootstrap_z = function(df){
  boot <- sample_n(df,           
                   size = NROW(df),
                   replace = TRUE)
  
  rates = boot %>%
        group_by(group) %>% 
        summarise(zero_results_rate = sum(results == 0)/n()) 
    
    group.a = rates %>% filter(group == "a") %>% pull(zero_results_rate)
    group.b = rates %>% filter(group == "b") %>% pull(zero_results_rate)
    
    diff <- group.a - group.b 
  
  return(diff)
}

repeticoes <- 2000
reamostragens_z = tibble(i = 1:repeticoes) %>% 
  mutate(theta_c_s_z = map_dbl(i, ~ bootstrap_z(buscas)))

erro.amostral.z = reamostragens_z %>% 
  mutate(erro = theta_c_s_z - theta_c_zero)

intervalo.z = erro.amostral.z %>% 
  summarise(erro_i = quantile(erro, .025), 
            erro_s = quantile(erro, .975))
intervalo.z

ci.z = intervalo.z %>% 
  mutate(valor_i = theta_c_zero + erro_i, 
         valor_s = theta_c_zero + erro_s)
ci.z$valor_i
ci.z$valor_s

```




